2025-10-02 15:53:28,134 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 15:57:39,122 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 16:29:44,947 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 16:30:30,484 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 16:31:18,779 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 16:37:34,060 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 20:58:29,039 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:02:34,168 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:05:06,406 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:05:19,955 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:05:32,958 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:13:51,193 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:13:55,364 ERROR: Exception on /portfolio/1 [GET] [in /home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/app/main/routes.py", line 56, in project
    return render_template('project.html', project=project_data, title='Portfolio')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/hagen/Projects/homepage/app/templates/project.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/hagen/Projects/homepage/app/templates/base.html", line 60, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/app/templates/project.html", line 153, in block 'content'
    <img src="{{ technology.thumbnail_url }}" />
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/app/models.py", line 224, in thumbnail_url
    return url_for('static', filename=self.thumbnail_url , _external=True)
                                      ^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/app/models.py", line 224, in thumbnail_url
    return url_for('static', filename=self.thumbnail_url , _external=True)
                                      ^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/app/models.py", line 224, in thumbnail_url
    return url_for('static', filename=self.thumbnail_url , _external=True)
                                      ^^^^^^^^^^^^^^^^^^
  [Previous line repeated 974 more times]
RecursionError: maximum recursion depth exceeded
2025-10-02 21:16:33,964 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:18:06,675 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:21:36,795 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:21:45,253 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:45:02,110 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:45:10,166 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:45:16,106 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:45:41,077 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:48:16,118 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:48:19,376 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:48:23,260 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:48:26,860 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:49:51,821 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:52:32,300 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:52:37,605 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:52:42,432 ERROR: Exception on /portfolio/1 [GET] [in /home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hagen/Projects/homepage/app/main/routes.py", line 54, in project
    print(x.name)
          ^^^^^^
AttributeError: 'Technology' object has no attribute 'name'
2025-10-02 21:53:39,544 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:56:00,909 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 21:58:22,958 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 22:00:22,963 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 22:08:07,359 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
2025-10-02 22:08:28,246 INFO: app startup [in /home/hagen/Projects/homepage/app/__init__.py:37]
